[package]
name = "day24"
version = "0.1.0"
edition = "2021"
description = "Advent of Code 2022 Day 24"

[dependencies]
bitflags = "1.3.2"
thiserror = "1.0"
utils = { version = "0.1", path = "../utils" }
